<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>PeopleSyncD.Api</RootNamespace>
    <AssemblyName>PeopleSyncD.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PeopleSyncD.Application/PeopleSyncD.Application.csproj" />
    <ProjectReference Include="../PeopleSyncD.Infrastructure/PeopleSyncD.Infrastructure.csproj" />
    <ProjectReference Include="../PeopleSyncD.ServiceDefaults/PeopleSyncD.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
  </ItemGroup>
</Project>
