<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PeopleSyncD.AppHost</RootNamespace>
    <AssemblyName>PeopleSyncD.AppHost</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PeopleSyncD.Api/PeopleSyncD.Api.csproj" />
  </ItemGroup>
</Project>
