<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <RootNamespace>PeopleSyncD.AppHost</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../PeopleSyncD.Api/PeopleSyncD.Api.csproj" />
  </ItemGroup>
</Project>
