apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: peoplesyncd-api
  namespace: peoplesyncd
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: peoplesyncd-api
