<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>PeopleSyncD.Application</RootNamespace>
    <AssemblyName>PeopleSyncD.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PeopleSyncD.Domain/PeopleSyncD.Domain.csproj" />
    <ProjectReference Include="../PeopleSyncD.SharedKernel/PeopleSyncD.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>
