receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
  batch: {}
  attributes/privacy:
    actions:
      - key: http.request.header.authorization
        action: delete
      - key: enduser.id
        action: hash
exporters:
  otlp:
    endpoint: ${env:PEOPLESYNCD_OTEL_EXPORTER_ENDPOINT}
    tls:
      insecure: false
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes/privacy, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, attributes/privacy, batch]
      exporters: [otlp]
